// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpjiszKlVow0KSvQxejjQuThXyTMj6BMw',
    appId: '1:80006833333:web:301b6bbbbd5ac48ae90afc',
    messagingSenderId: '80006833333',
    projectId: 'goochi-brew-crew',
    authDomain: 'goochi-brew-crew.firebaseapp.com',
    storageBucket: 'goochi-brew-crew.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtLkYfOjNxG0cv4JavDPXA20u22tBX_Hk',
    appId: '1:80006833333:android:d06b32238d5732cbe90afc',
    messagingSenderId: '80006833333',
    projectId: 'goochi-brew-crew',
    storageBucket: 'goochi-brew-crew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYUjHuONhkYMkwZY3OEHE7nNkxdGDqUsM',
    appId: '1:80006833333:ios:c1d9039a820255ece90afc',
    messagingSenderId: '80006833333',
    projectId: 'goochi-brew-crew',
    storageBucket: 'goochi-brew-crew.appspot.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYUjHuONhkYMkwZY3OEHE7nNkxdGDqUsM',
    appId: '1:80006833333:ios:9dd311ca8c69d8a3e90afc',
    messagingSenderId: '80006833333',
    projectId: 'goochi-brew-crew',
    storageBucket: 'goochi-brew-crew.appspot.com',
    iosBundleId: 'com.example.brewCrew.RunnerTests',
  );
}
